name: 'Assets'

on:
  create:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'

jobs:
  webpack:
    name: 'Build Assets'

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Using Node"
        uses: "actions/setup-node@v3.1.0"

      - name: "Install dependencies"
        run: "yarn"

      - name: "Build"
        run: "yarn build"

      - name: "Check size"
        run: "yarn size"
